let pokemonList = [
    {
        id: 0o0001,
        name: 'Bulbasaur',
        height: '.7m',
        types: ['Grass', 'Poison'], 
        hp: 45,
        attack: 49,
        defense: 49,
        speed: 45,
        spAttack: 65,
        spDefense: 65,
    },
    {
    id:0o0002,
    name:'Ivysaur',
    height: '1m',
    types:['Grass', 'Poison'], 
    hp: 60,
    attack: 62,
    defense: 63,
    speed: 60,
    spAttack: 80,
    spDefense: 80,
    },
    {
        id:0o0003,
        name:'Veusaur',
        height: '2m',
        types:['Grass', 'Poison'], 
        hp: 80,
        attack: 82,
        defense: 83,
        speed: 80,
        spAttack: 100,
        spDefense: 100,
        },
        {
            id:0o0004,
            name:'Charmander',
            height: '.6m',
            types:['Fire'], 
            hp: 39,
            attack: 52,
            defense: 43,
            speed: 65,
            spAttack: 60,
            spDefense: 50,
            },
            {
                id:0o0005,
                name:'Charmeleon',
                height: '1.1m',
                types:['Fire'], 
                hp: 58,
                attack: 64,
                defense: 58,
                speed: 80,
                spAttack: 80,
                spDefense: 65,
                },
                {
                    id:0o0006,
                    name:'Charizard',
                    height: '1.7m',
                    types:['Fire', 'Flying'], 
                    hp: 78,
                    attack: 84,
                    defense: 78,
                    speed: 100,
                    spAttack: 109,
                    spDefense: 85,
                    },
                    {
                        id:0o0007,
                        name:'Squirtle',
                        height: '.5m',
                        types:['Water'], 
                        hp: 44,
                        attack: 48,
                        defense: 65,
                        speed: 43,
                        spAttack: 50,
                        spDefense: 64,
                        },
];